# Generated by Django 3.0.3 on 2020-03-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShop', '0002_auto_20200320_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price_to_pay',
            new_name='total_price_of_an_item',
        ),
    ]
