# Generated by Django 3.0.3 on 2020-02-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20200211_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='tags',
        ),
    ]
