# Generated by Django 3.0.3 on 2020-02-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_task_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
